### ISSUE TITLE
Heroku deploy failing.

### ISSUE THREAD

**Issue by VitorSDDF** [MicroPyramid/django-blog-it#120]
-----> Python app detected
-----> Installing python-3.6.8
-----> Installing pip
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting boto==2.40.0 (from -r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 1))
         Downloading https://files.pythonhosted.org/packages/41/b4/f788bf1ed5f35f2dc29410f41a38688584d25babbfdf2528b09e00a77438/boto-2.40.0-py2.py3-none-any.whl (1.3MB)
       Collecting Django==1.11.21 (from -r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 2))
         Downloading https://files.pythonhosted.org/packages/a2/84/9f66e359ba8e63cf9b54f6815ed55188dda43cd1cc951a8bb95542dee956/Django-1.11.21-py2.py3-none-any.whl (6.9MB)
       Collecting django-simple-pagination==1.1.4 (from -r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 3))
         Downloading https://files.pythonhosted.org/packages/68/b8/2d27c49f1a500e67d05501c3b5aecf02800cfd6d534cd2e79fa6c631932e/django-simple-pagination-1.1.4.tar.gz
       Collecting django-storages==1.4.1 (from -r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 4))
         Downloading https://files.pythonhosted.org/packages/14/94/0a90cd3e36a0db7a46126aad0c91a5365b0fbb94de378c198afae9740645/django_storages-1.4.1-py2.py3-none-any.whl (41kB)
       Collecting Pillow==4.3.0 (from -r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 5))
         Downloading https://files.pythonhosted.org/packages/3c/5c/44a8f05da34cbb495e5330825c2204b9fa761357c87bc0bc1785b1d76e41/Pillow-4.3.0-cp36-cp36m-manylinux1_x86_64.whl (5.8MB)
       Collecting requests==2.20.0 (from -r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 6))
         Downloading https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl (60kB)
       Collecting gunicorn==19.6.0 (from -r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 7))
         Downloading https://files.pythonhosted.org/packages/72/de/ec28a64885e0b390063379cca601b60b1f9e51367e0c76030ac8a5cddd5e/gunicorn-19.6.0-py2.py3-none-any.whl (114kB)
       Collecting whitenoise==3.1 (from -r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 8))
         Downloading https://files.pythonhosted.org/packages/3f/6d/020ae7ab9b53e1969a6c2f7e985b9296c7e820305405249fdf18d271282c/whitenoise-3.1-py2.py3-none-any.whl
       Collecting dj-database-url==0.4.1 (from -r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 9))
         Downloading https://files.pythonhosted.org/packages/39/9f/30f937db9f9e7a4e4e3205682af4c34c65d647ff9850897ddfbbf5dc6178/dj-database-url-0.4.1.tar.gz
       Collecting psycopg2==2.7.1 (from -r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 10))
         Downloading https://files.pythonhosted.org/packages/90/bb/fd1a81e1a51b2df2d825e778fd58d508a4fc9ab360684348222bda3ff704/psycopg2-2.7.1-cp36-cp36m-manylinux1_x86_64.whl (2.7MB)
       Collecting microurl==0.1.1 (from -r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 11))
         Downloading https://files.pythonhosted.org/packages/8b/79/d095ee579956afa6dd7d5bd7da6c2c0b014ab0db191e433f7684dab75675/microurl-0.1.1.tar.gz
       Collecting pytz (from Django==1.11.21->-r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 2))
         Downloading https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl (508kB)
       Collecting olefile (from Pillow==4.3.0->-r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 5))
         Downloading https://files.pythonhosted.org/packages/34/81/e1ac43c6b45b4c5f8d9352396a14144bba52c8fec72a80f425f6a4d653ad/olefile-0.46.zip (112kB)
       Collecting certifi>=2017.4.17 (from requests==2.20.0->-r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 6))
         Downloading https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl (157kB)
       Collecting idna<2.8,>=2.5 (from requests==2.20.0->-r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 6))
         Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
       Collecting chardet<3.1.0,>=3.0.2 (from requests==2.20.0->-r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 6))
         Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
       Collecting urllib3<1.25,>=1.21.1 (from requests==2.20.0->-r /tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/requirements.txt (line 6))
         Downloading https://files.pythonhosted.org/packages/01/11/525b02e4acc0c747de8b6ccdab376331597c569c42ea66ab0a1dbd36eca2/urllib3-1.24.3-py2.py3-none-any.whl (118kB)
       Installing collected packages: boto, pytz, Django, django-simple-pagination, django-storages, olefile, Pillow, certifi, idna, chardet, urllib3, requests, gunicorn, whitenoise, dj-database-url, psycopg2, microurl
         Running setup.py install for django-simple-pagination: started
           Running setup.py install for django-simple-pagination: finished with status 'done'
         Running setup.py install for olefile: started
           Running setup.py install for olefile: finished with status 'done'
         Running setup.py install for dj-database-url: started
           Running setup.py install for dj-database-url: finished with status 'done'
         Running setup.py install for microurl: started
           Running setup.py install for microurl: finished with status 'done'
       Successfully installed Django-1.11.21 Pillow-4.3.0 boto-2.40.0 certifi-2019.6.16 chardet-3.0.4 dj-database-url-0.4.1 django-simple-pagination-1.1.4 django-storages-1.4.1 gunicorn-19.6.0 idna-2.7 microurl-0.1.1 olefile-0.46 psycopg2-2.7.1 pytz-2019.2 requests-2.20.0 urllib3-1.24.3 whitenoise-3.1
-----> $ python sandbox/manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "sandbox/manage.py", line 10, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
           collected = self.collect()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 115, in collect
           for path, storage in finder.list(self.ignore_patterns):
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/finders.py", line 112, in list
           for path in utils.get_files(storage, ignore_patterns):
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
           directories, files = storage.listdir(location)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/files/storage.py", line 397, in listdir
           for entry in os.listdir(path):
       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/build_a3434d6dd43d5544a2406f6b655b3189/sandbox/static'
 !     Error while running '$ python sandbox/manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by shoomkloom** [comment]
Happens to me too

**Comment by mirfan899** [comment]
same issue here
